baseURL = "http://example.org/"
languageCode = "en-us"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
debug = true


[languages]
    [languages.en]
        languageName = "English"
        title = "My New Hugo Site"
        weight = 1

    [languages.pl]
        languageName = "Polski"
        title = "Moja strona w Hugo"
        weight = 2